"""AI Reviewer Agent - reviews pull requests and provides feedback."""

import logging
from typing import Any

from code_agent.config import settings
from code_agent.core.github_client import GitHubClient
from code_agent.core.llm import LLMService

logger = logging.getLogger(__name__)


class ReviewerAgent:
    """Agent that reviews pull requests and provides feedback."""

    def __init__(
        self,
        github_client: GitHubClient | None = None,
        llm_service: LLMService | None = None,
    ) -> None:
        """Initialize Reviewer Agent."""
        self.github_client = github_client or GitHubClient()
        self.llm_service = llm_service or LLMService()

    def review_pull_request(self, pr_number: int) -> dict[str, Any]:
        """Review a pull request and provide feedback."""
        logger.info(f"Reviewing PR #{pr_number}")
        logger.info(
            "Review target repo=%s (api_repo_url=%s)",
            getattr(self.github_client, "repo_name", "unknown"),
            getattr(getattr(self.github_client, "repo", None), "url", "unknown"),
        )

        # Get PR details
        pr = self.github_client.get_pull_request(pr_number)

        # Extract issue number
        issue_number = self._extract_issue_number(pr.body or "")

        if not issue_number:
            logger.warning("Could not find related issue number")
            issue_description = pr.title
        else:
            issue_details = self.github_client.get_issue_details(issue_number)
            issue_description = f"{issue_details['title']}\n\n{issue_details['body']}"

        # Get PR diff
        pr_diff = self.github_client.get_pr_diff(pr_number)

        if not pr_diff.strip():
            logger.warning("PR has no changes")
            return {
                "approved": False,
                "feedback": "No changes detected in this PR.",
                "issues": ["No code changes found"],
            }

        # Get CI/CD results
        ci_results = None
        if settings.enable_ci_analysis:
            try:
                checks = self.github_client.get_pr_checks(pr_number)
                ci_results = self._format_ci_results(checks)
            except Exception as e:
                logger.warning(f"Could not get CI results: {e}")

        # Perform code review using LLM
        review_result = self.llm_service.review_code_changes(
            pr_diff, issue_description, ci_results
        )

        logger.info(f"Review complete: {'approved' if review_result['approved'] else 'changes requested'}")

        # Post review to GitHub
        self._post_review(pr_number, review_result)

        return review_result

    def _format_ci_results(self, checks: list[dict[str, Any]]) -> str:
        """Format CI/CD check results."""
        if not checks:
            return "No CI checks found."

        result = "CI/CD Check Results:\n\n"
        for check in checks:
            status = check.get("conclusion", check.get("status", "unknown"))
            result += f"- {check['name']}: {status}\n"
            if check.get("output"):
                result += f"  {check['output'][:200]}\n"

        return result

    def _post_review(self, pr_number: int, review_result: dict[str, Any]) -> None:
        """Post review results to GitHub PR."""
        approved = review_result.get("approved", False)
        feedback = review_result.get("feedback", "")
        issues = review_result.get("issues", [])

        # Determine review event
        if approved:
            event = "APPROVE"
            body = f"✅ **Code Review: APPROVED**\n\n{feedback}"
        else:
            event = "REQUEST_CHANGES"
            body = f"🔍 **Code Review: Changes Requested**\n\n{feedback}"

            if issues:
                body += "\n\n**Issues Found:**\n"
                for i, issue in enumerate(issues, 1):
                    body += f"{i}. {issue}\n"

        body += "\n\n---\n*This review was automatically generated by AI Reviewer Agent.*"

        try:
            self.github_client.create_review(
                pr_number=pr_number,
                body=body,
                event=event,
            )
            logger.info(f"Posted review to PR #{pr_number}")
        except Exception as e:
            logger.error(f"Error posting review: {e}")
            # Fallback to comment
            try:
                self.github_client.add_comment_to_pr(pr_number, body)
                logger.info(f"Posted fallback comment to PR #{pr_number}")
            except Exception as e2:
                # Don't fail the run if we don't have permission to write to the repo.
                logger.error(f"Error posting fallback comment: {e2}")

    def _extract_issue_number(self, text: str) -> int | None:
        """Extract issue number from text."""
        import re

        match = re.search(r"#(\d+)", text)
        if match:
            return int(match.group(1))

        return None

    def generate_review_summary(self, pr_number: int) -> str:
        """Generate a summary of the review for GitHub Actions."""
        logger.info(f"Generating review summary for PR #{pr_number}")

        try:
            review_result = self.review_pull_request(pr_number)

            summary = "# 🤖 AI Code Review Summary\n\n"

            if review_result.get("approved"):
                summary += "## ✅ Status: APPROVED\n\n"
                summary += "The code changes look good and meet the requirements.\n\n"
            else:
                summary += "## ⚠️ Status: CHANGES REQUESTED\n\n"
                summary += "Some issues were found that need to be addressed.\n\n"

            summary += "## 📝 Feedback\n\n"
            summary += review_result.get("feedback", "No feedback provided.")
            summary += "\n\n"

            issues = review_result.get("issues", [])
            if issues:
                summary += "## 🐛 Issues Found\n\n"
                for i, issue in enumerate(issues, 1):
                    summary += f"{i}. {issue}\n"
                summary += "\n"

            summary += "---\n"
            summary += "*Generated by AI Reviewer Agent*\n"

            return summary

        except Exception as e:
            logger.error(f"Error generating review summary: {e}")
            return f"# ❌ Review Error\n\nFailed to generate review: {str(e)}"

